window.caravanPlaces=[
  {
    "id": "asikkala-kanavaanari",
    "name": "Kanavaanari – Vääksyn matkaparkki",
    "city": "Asikkala",
    "address": "Melakuja 4, 17200 Vääksy",
    "description": "Matkaparkki Vääksyn kanavan ja Päijännetalon lähellä.",
    "type": "park",
    "url": "asikkala-kanavaanari.html",
    "map": "",
    "navigate": ""
  },
  {
    "id": "camping-tallukka",
    "name": "Tallukan matkaparkki",
    "city": "Asikkala",
    "address": "Tallukantie 1, 17200 Vääksy",
    "description": "Matkaparkki Hotelli Tallukan yhteydessä.",
    "type": "park",
    "url": "camping-tallukka.html",
    "map": "https://www.google.com/maps/search/?api=1&query=Tallukan+matkaparkki+Tallukantie+1%2C+17200+V%C3%A4%C3%A4ksy",
    "navigate": "https://www.google.com/maps/dir/?api=1&destination=Tallukantie+1%2C+17200+V%C3%A4%C3%A4ksy"
  },
  {
    "id": "camping-koskenniemi",
    "name": "Camping Koskenniemi",
    "city": "Hartola",
    "address": "Koskenniementie 66, 19600 Hartola",
    "description": "Leirintäalue ja majoituspalveluja Hartolassa.",
    "type": "camping",
    "url": "camping-koskenniemi.html",
    "map": "https://www.google.com/maps/search/?api=1&query=Camping+Koskenniemi+Koskenniementie+66%2C+19600+Hartola",
    "navigate": "https://www.google.com/maps/dir/?api=1&destination=Koskenniementie+66%2C+19600+Hartola"
  },
  {
    "id": "heinola-heinasaari",
    "name": "Camping Heinolan Heinäsaari",
    "city": "Heinola",
    "address": "Heinäsaarentie 101, 18100 Heinola",
    "description": "Leirintäalue, caravan-paikat, mökit, saunat ja ravintolapalveluja vesistömaisemissa.",
    "type": "camping",
    "url": "heinola-heinasaari.html",
    "map": "https://www.google.com/maps/search/?api=1&query=Camping+Heinolan+Hein%C3%A4saari+Hein%C3%A4saarentie+101%2C+18100+Heinola",
    "navigate": "https://www.google.com/maps/dir/?api=1&destination=Hein%C3%A4saarentie+101%2C+18100+Heinola"
  },
  {
    "id": "camping-vidnas",
    "name": "Camping Vidnäs",
    "city": "Heinola",
    "address": "Viikinäistentie 203 A, 19210 Lusi",
    "description": "Pieni leirintäalue maaseudun rauhassa järven rannalla; myös telttapaikkoja.",
    "type": "camping",
    "url": "camping-vidnas.html",
    "map": "https://www.google.com/maps/search/?api=1&query=Camping+Vidn%C3%A4s+Viikin%C3%A4istentie+203+A%2C+19210+Lusi",
    "navigate": "https://www.google.com/maps/dir/?api=1&destination=Viikin%C3%A4istentie+203+A%2C+19210+Lusi"
  },
  {
    "id": "hollola-messila",
    "name": "Camping Messilä",
    "city": "Hollola",
    "address": "Rantatie 5, 15980 Messilä",
    "description": "Camping-alue Vesijärven rannalla matkailuautoille, vaunuille ja telttailuun.",
    "type": "camping",
    "url": "hollola-messila.html",
    "map": "https://www.google.com/maps/search/?api=1&query=Camping+Messil%C3%A4+Rantatie+5%2C+15980+Messil%C3%A4",
    "navigate": "https://www.google.com/maps/dir/?api=1&destination=Rantatie+5%2C+15980+Messil%C3%A4"
  },
  {
    "id": "camping-leininranta",
    "name": "SFC Leininranta",
    "city": "Iitti",
    "address": "Siestantie 85, 47400 Kausala",
    "description": "SF-Caravan-alue Iitissä. Tarkista vierailuehdot ja aukiolo ennen saapumista.",
    "type": "camping",
    "url": "camping-leininranta.html",
    "map": "https://www.google.com/maps/search/?api=1&query=SFC+Leininranta+Siestantie+85%2C+47400+Kausala",
    "navigate": "https://www.google.com/maps/dir/?api=1&destination=Siestantie+85%2C+47400+Kausala"
  },
  {
    "id": "camping-kangaslampi",
    "name": "SFC Kangaslampi",
    "city": "Lahti",
    "address": "Alhaistentie 77, 15560 Nastola",
    "description": "Caravan- ja leirintäalue Lahden Nastolassa. Tarkista vierailuehdot ennen saapumista.",
    "type": "camping",
    "url": "camping-kangaslampi.html",
    "map": "https://www.google.com/maps/search/?api=1&query=SFC+Kangaslampi+Alhaistentie+77%2C+15560+Nastola",
    "navigate": "https://www.google.com/maps/dir/?api=1&destination=Alhaistentie+77%2C+15560+Nastola"
  },
  {
    "id": "camping-hennala",
    "name": "Hennalan matkaparkki",
    "city": "Lahti",
    "address": "Pataljoonankatu 3, 15700 Lahti",
    "description": "Kaupunkimatkaparkki Hennalan alueella.",
    "type": "park",
    "url": "camping-hennala.html",
    "map": "https://www.google.com/maps/search/?api=1&query=Hennalan+matkaparkki+Pataljoonankatu+3%2C+15700+Lahti",
    "navigate": "https://www.google.com/maps/dir/?api=1&destination=Pataljoonankatu+3%2C+15700+Lahti"
  },
  {
    "id": "camping-herrasmanni",
    "name": "Herrasmannin leirintäalue",
    "city": "Lahti",
    "address": "Herrasmanninkatu 20, 15210 Lahti",
    "description": "Leirintä- ja caravan-alue Alasenjärven rannalla.",
    "type": "camping",
    "url": "camping-herrasmanni.html",
    "map": "https://www.google.com/maps/search/?api=1&query=Herrasmannin+leirint%C3%A4alue+Herrasmanninkatu+20%2C+15210+Lahti",
    "navigate": "https://www.google.com/maps/dir/?api=1&destination=Herrasmanninkatu+20%2C+15210+Lahti"
  },
  {
    "id": "camping-lokki",
    "name": "Ravintola Lokin matkaparkki",
    "city": "Lahti",
    "address": "Jalkarannantie 19, 15900 Lahti",
    "description": "Matkaparkki Vesijärven ja sataman läheisyydessä.",
    "type": "park",
    "url": "camping-lokki.html",
    "map": "https://www.google.com/maps/search/?api=1&query=Ravintola+Lokin+matkaparkki+Jalkarannantie+19%2C+15900+Lahti",
    "navigate": "https://www.google.com/maps/dir/?api=1&destination=Jalkarannantie+19%2C+15900+Lahti"
  },
  {
    "id": "camping-telaranta",
    "name": "Lomakeskus Telaranta Camping",
    "city": "Padasjoki",
    "address": "Porasantie 176, 17500 Padasjoki",
    "description": "Camping- ja lomakeskus Padasjoen luonnon keskellä.",
    "type": "camping",
    "url": "camping-telaranta.html",
    "map": "https://www.google.com/maps/search/?api=1&query=Lomakeskus+Telaranta+Camping+Porasantie+176%2C+17500+Padasjoki",
    "navigate": "https://www.google.com/maps/dir/?api=1&destination=Porasantie+176%2C+17500+Padasjoki"
  },
  {
    "id": "camping-mainiemi",
    "name": "Mainiemi Caravan",
    "city": "Padasjoki",
    "address": "Pykäläniementie 10, 17500 Padasjoki",
    "description": "Caravan-alue Padasjoella. Tarkista vierailuehdot ja aukiolo ennen saapumista.",
    "type": "camping",
    "url": "camping-mainiemi.html",
    "map": "https://www.google.com/maps/search/?api=1&query=Mainiemi+Caravan+Pyk%C3%A4l%C3%A4niementie+10%2C+17500+Padasjoki",
    "navigate": "https://www.google.com/maps/dir/?api=1&destination=Pyk%C3%A4l%C3%A4niementie+10%2C+17500+Padasjoki"
  },
  {
    "id": "camping-mylly-makela",
    "name": "SFC Mylly-Mäkelä",
    "city": "Padasjoki",
    "address": "Mylly-Mäkeläntie 14, 17530 Arrakoski",
    "description": "Ympärivuotinen caravan- ja leirintäalue järven ja kosken äärellä.",
    "type": "camping",
    "url": "camping-mylly-makela.html",
    "map": "https://www.google.com/maps/search/?api=1&query=SFC+Mylly-M%C3%A4kel%C3%A4+Mylly-M%C3%A4kel%C3%A4ntie+14%2C+17530+Arrakoski",
    "navigate": "https://www.google.com/maps/dir/?api=1&destination=Mylly-M%C3%A4kel%C3%A4ntie+14%2C+17530+Arrakoski"
  },
  {
    "id": "camping-vuorenmaki",
    "name": "SFC Vuorenmäki",
    "city": "Orimattila",
    "address": "Salmelantie 178, 16200 Artjärvi",
    "description": "Ympärivuotinen caravanalue Villikkalanjärven läheisyydessä Artjärvellä.",
    "type": "camping",
    "url": "camping-vuorenmaki.html",
    "map": "https://www.google.com/maps/search/?api=1&query=SFC+Vuorenm%C3%A4ki+Salmelantie+178%2C+16200+Artj%C3%A4rvi",
    "navigate": "https://www.google.com/maps/dir/?api=1&destination=Salmelantie+178%2C+16200+Artj%C3%A4rvi"
  },
  {
    "id": "camping-sysma",
    "name": "Camping Sysmä",
    "city": "Sysmä",
    "address": "Huitilantie 3, 19700 Sysmä",
    "description": "Leirintäalue Päijänteen rannalla matkailuautoille, vaunuille, teltoille ja mökkimajoitukseen.",
    "type": "camping",
    "url": "camping-sysma.html",
    "map": "https://www.google.com/maps/search/?api=1&query=Camping+Sysm%C3%A4+Huitilantie+3%2C+19700+Sysm%C3%A4",
    "navigate": "https://www.google.com/maps/dir/?api=1&destination=Huitilantie+3%2C+19700+Sysm%C3%A4"
  },
  {
    "id": "porvoo-pellinge-caravan",
    "name": "Pellinge Caravan",
    "city": "Porvoo",
    "address": "Santasaarentie 128, Pellinge",
    "description": "Karavaanipaikka Porvoon saaristossa. Tarkista palvelut ja aukiolo ennen saapumista.",
    "type": "camping",
    "url": "porvoo-karavaanari.html",
    "map": "https://www.google.com/maps/search/?api=1&query=Pellinge+Caravan+Santasaarentie+128+Pellinge",
    "navigate": "https://www.google.com/maps/dir/?api=1&destination=Santasaarentie+128+Pellinge"
  },
  {
    "id": "porvoo-skeppars",
    "name": "SFC Skeppars",
    "city": "Porvoo",
    "address": "Hummelpärantie 161, Porvoo",
    "description": "SF-Caravan-alue Porvoossa. Tarkista vierailuehdot ja aukiolo ennen saapumista.",
    "type": "camping",
    "url": "porvoo-karavaanari.html",
    "map": "https://www.google.com/maps/search/?api=1&query=SFC+Skeppars+Hummelp%C3%A4rantie+161+Porvoo",
    "navigate": "https://www.google.com/maps/dir/?api=1&destination=Hummelparantie+161+Porvoo"
  },
  {
    "id": "loviisa-camping",
    "name": "Loviisa Camping",
    "city": "Loviisa",
    "address": "Kapteenintie 1, Loviisa",
    "description": "Asuntoauto- ja asuntovaunupaikkoja, suihkut, sauna, uimaranta, Wi-Fi ja septitankin tyhjennys.",
    "type": "camping",
    "url": "loviisa-karavaanari.html",
    "map": "https://www.google.com/maps/search/?api=1&query=Loviisa+Camping+Kapteenintie+1",
    "navigate": "https://www.google.com/maps/dir/?api=1&destination=Kapteenintie+1+Loviisa"
  },
  {
    "id": "loviisan-matkaparkki",
    "name": "Loviisan matkaparkki",
    "city": "Loviisa",
    "address": "Sibeliuksenkatu 3, Loviisa",
    "description": "Keskustan matkaparkki. Tarkista paikat, palvelut ja käyttöehdot ennen saapumista.",
    "type": "park",
    "url": "loviisa-karavaanari.html",
    "map": "https://www.google.com/maps/search/?api=1&query=Loviisan+matkaparkki+Sibeliuksenkatu+3",
    "navigate": "https://www.google.com/maps/dir/?api=1&destination=Sibeliuksenkatu+3+Loviisa"
  },
  {
    "id": "jyvaskyla-laajis",
    "name": "Laajis Urban Caravan",
    "city": "Jyväskylä",
    "address": "Laajavuorentie 15, 40740 Jyväskylä",
    "description": "Urban Caravan -kohde Jyväskylän Laajavuoressa.",
    "type": "camping",
    "url": "jyvaskyla-karavaanari.html",
    "map": "https://www.google.com/maps/search/?api=1&query=Laajis+Urban+Caravan+Laajavuorentie+15+Jyväskylä",
    "navigate": "https://www.google.com/maps/dir/?api=1&destination=Laajavuorentie+15+Jyväskylä"
  },
  {
    "id": "jyvaskyla-lutakko",
    "name": "Jyväskylän Lutakon sataman matkaparkki",
    "city": "Jyväskylä",
    "address": "Lutakon satama, Jyväskylä",
    "description": "Kuusi matkailuautopaikkaa keskustan ja matkakeskuksen lähellä. Ei sähköä; yöpyminen sallittu, leiriytyminen kielletty.",
    "type": "park",
    "url": "jyvaskyla-karavaanari.html",
    "map": "https://www.google.com/maps/search/?api=1&query=Jyväskylän+Lutakon+satama",
    "navigate": "https://www.google.com/maps/dir/?api=1&destination=Jyväskylän+Lutakon+satama"
  },
  {
    "id": "tampere-camping-harmala",
    "name": "Camping Härmälä",
    "city": "Tampere",
    "address": "Tampere",
    "description": "Camping- ja caravan-kohde Tampereella. Tarkista ajantasaiset palvelut ja aukiolo kohteen omalta sivulta.",
    "type": "camping",
    "url": "tampere-karavaanari.html",
    "map": "https://www.google.com/maps/search/?api=1&query=Camping+Härmälä+Tampere",
    "navigate": "https://www.google.com/maps/dir/?api=1&destination=Camping+Härmälä+Tampere"
  },
  {
    "id": "tampere-niihama",
    "name": "Niihaman ulkoilumajan camping",
    "city": "Tampere",
    "address": "Niihama, Tampere",
    "description": "Camping-kohde Tampereen seudulla. Tarkista palvelut, paikat ja aukiolo ennen saapumista.",
    "type": "camping",
    "url": "tampere-karavaanari.html",
    "map": "https://www.google.com/maps/search/?api=1&query=Niihaman+ulkoilumaja+Tampere",
    "navigate": "https://www.google.com/maps/dir/?api=1&destination=Niihaman+ulkoilumaja+Tampere"
  },
  {
    "id": "helsinki-rastila",
    "name": "Rastila Camping Helsinki",
    "city": "Helsinki",
    "address": "Karavaanikatu 4, 00980 Helsinki",
    "description": "Ympärivuotinen viiden tähden leirintäalue merellisessä Vuosaaressa metron lähellä.",
    "type": "camping",
    "url": "uusimaa-karavaanari.html#helsinki",
    "map": "https://www.google.com/maps/search/?api=1&query=Rastila+Camping+Helsinki",
    "navigate": "https://www.google.com/maps/dir/?api=1&destination=Karavaanikatu+4+Helsinki"
  },
  {
    "id": "espoo-pirttimaki",
    "name": "Pirttimäki Camping",
    "city": "Espoo",
    "address": "Kunnarlantie 110, 02740 Espoo",
    "description": "Luonnonläheinen camping-alue Espoossa. Tarkista aukiolo ja palvelut ennen saapumista.",
    "type": "camping",
    "url": "uusimaa-karavaanari.html#espoo",
    "map": "https://www.google.com/maps/search/?api=1&query=Pirttimäki+Camping+Espoo",
    "navigate": "https://www.google.com/maps/dir/?api=1&destination=Kunnarlantie+110+Espoo"
  },
  {
    "id": "espoo-backby",
    "name": "Backbyn Kartano",
    "city": "Espoo",
    "address": "Bodomintie 37, 02740 Espoo",
    "description": "Matkailuajoneuvoille sopiva yöpymispaikka kartanon yhteydessä.",
    "type": "park",
    "url": "uusimaa-karavaanari.html#espoo",
    "map": "https://www.google.com/maps/search/?api=1&query=Backbyn+Kartano+Espoo",
    "navigate": "https://www.google.com/maps/dir/?api=1&destination=Bodomintie+37+Espoo"
  },
  {
    "id": "kirkkonummi-friggesby",
    "name": "Friggesby",
    "city": "Kirkkonummi",
    "address": "Friggesbyntie 44, 02480 Kirkkonummi",
    "description": "Rauhallinen yöpymispaikka Kirkkonummella. Tarkista saatavuus ennen saapumista.",
    "type": "park",
    "url": "uusimaa-karavaanari.html#kirkkonummi",
    "map": "https://www.google.com/maps/search/?api=1&query=Friggesby+Kirkkonummi",
    "navigate": "https://www.google.com/maps/dir/?api=1&destination=Friggesbyntie+44+Kirkkonummi"
  },
  {
    "id": "sipoo-jokirannan-kartano",
    "name": "Jokirannan Kartano",
    "city": "Sipoo",
    "address": "Peltotie 34, 01490 Sipoo",
    "description": "Maaseutumainen matkaparkki Sipoossa. Tarkista palvelut ja varattavuus.",
    "type": "park",
    "url": "uusimaa-karavaanari.html#sipoo",
    "map": "https://www.google.com/maps/search/?api=1&query=Jokirannan+Kartano+Sipoo",
    "navigate": "https://www.google.com/maps/dir/?api=1&destination=Peltotie+34+Sipoo"
  },
  {
    "id": "vihti-varikko",
    "name": "Varikko",
    "city": "Vihti",
    "address": "Helsingintie 25, 03400 Vihti",
    "description": "Edullinen matkaparkki Vihdissä. Tarkista palvelut ja käyttöehdot.",
    "type": "park",
    "url": "uusimaa-karavaanari.html#vihti",
    "map": "https://www.google.com/maps/search/?api=1&query=Varikko+Helsingintie+25+Vihti",
    "navigate": "https://www.google.com/maps/dir/?api=1&destination=Helsingintie+25+Vihti"
  },
  {
    "id": "vihti-vihtipark",
    "name": "SFC VihtiPark",
    "city": "Vihti",
    "address": "Rauhaniementie 391, 03790 Vihtijärvi",
    "description": "SF-Caravan-alue Vihtijärvellä. Tarkista vierailuehdot ja isäntäpäivystys.",
    "type": "camping",
    "url": "uusimaa-karavaanari.html#vihti",
    "map": "https://www.google.com/maps/search/?api=1&query=SFC+VihtiPark",
    "navigate": "https://www.google.com/maps/dir/?api=1&destination=Rauhaniementie+391+Vihtijärvi"
  },
  {
    "id": "vihti-etelalahti",
    "name": "SFC Etelälahti",
    "city": "Vihti",
    "address": "Ollilantie 225 A, 03300 Otalampi",
    "description": "Kaikille avoin SF-Caravan-leirintäalue Otalammella.",
    "type": "camping",
    "url": "uusimaa-karavaanari.html#vihti",
    "map": "https://www.google.com/maps/search/?api=1&query=SFC+Etelälahti+Otalampi",
    "navigate": "https://www.google.com/maps/dir/?api=1&destination=Ollilantie+225+A+Otalampi"
  },
  {
    "id": "tuusula-onni",
    "name": "Pieni Kotieläintila ja Kahvila Onni",
    "city": "Tuusula",
    "address": "Santavillantie 78, 04380 Tuusula",
    "description": "Matkaparkki kotieläintilan ja kahvilan yhteydessä; myös sähköpaikkoja.",
    "type": "park",
    "url": "uusimaa-karavaanari.html#tuusula",
    "map": "https://www.google.com/maps/search/?api=1&query=Kotieläintila+Kahvila+Onni+Tuusula",
    "navigate": "https://www.google.com/maps/dir/?api=1&destination=Santavillantie+78+Tuusula"
  },
  {
    "id": "inkoo-matkaparkki",
    "name": "Inkoon matkaparkki",
    "city": "Inkoo",
    "address": "Suurkirkontie 9, 10210 Inkoo",
    "description": "Keskustan matkaparkki Inkoossa. Tarkista saatavuus ja palvelut ennen saapumista.",
    "type": "park",
    "url": "uusimaa-karavaanari.html#inkoo",
    "map": "https://www.google.com/maps/search/?api=1&query=Inkoon+matkaparkki",
    "navigate": "https://www.google.com/maps/dir/?api=1&destination=Suurkirkontie+9+Inkoo"
  },
  {
    "id": "jarvenpaa-pajula",
    "name": "Pajula Matkaparkki",
    "city": "Järvenpää",
    "address": "Kiteentie 16, 04410 Järvenpää",
    "description": "Rauhallinen matkaparkki Järvenpäässä; saatavilla sähköpaikkoja.",
    "type": "park",
    "url": "uusimaa-karavaanari.html#jarvenpaa",
    "map": "https://www.google.com/maps/search/?api=1&query=Pajula+Matkaparkki+Järvenpää",
    "navigate": "https://www.google.com/maps/dir/?api=1&destination=Kiteentie+16+Järvenpää"
  },
  {
    "id": "raasepori-lovdal",
    "name": "Lövdal",
    "city": "Raasepori",
    "address": "Sotilastorpantie 90, 10380 Raasepori",
    "description": "Matkaparkki Raaseporissa; sähkö-, WC- ja vesipalveluja.",
    "type": "park",
    "url": "uusimaa-karavaanari.html#raasepori",
    "map": "https://www.google.com/maps/search/?api=1&query=Lövdal+Raasepori",
    "navigate": "https://www.google.com/maps/dir/?api=1&destination=Sotilastorpantie+90+Raasepori"
  },
  {
    "id": "raasepori-tammisaari-camping",
    "name": "Tammisaari Camping Ekenäs",
    "city": "Raasepori",
    "address": "Pursitie 1, 10600 Tammisaari",
    "description": "Leirintäalue luonnonpuiston vieressä lähellä Tammisaaren keskustaa.",
    "type": "camping",
    "url": "uusimaa-karavaanari.html#raasepori",
    "map": "https://www.google.com/maps/search/?api=1&query=Tammisaari+Camping+Ekenäs",
    "navigate": "https://www.google.com/maps/dir/?api=1&destination=Pursitie+1+Tammisaari"
  },
  {
    "id": "raasepori-kopparo",
    "name": "Kopparö Tammisaari",
    "city": "Raasepori",
    "address": "Kopparö, Tammisaari",
    "description": "Monipuolinen leirintäalue meren äärellä, myös matkailuauto- ja vaunupaikkoja.",
    "type": "camping",
    "url": "uusimaa-karavaanari.html#raasepori",
    "map": "https://www.google.com/maps/search/?api=1&query=Kopparö+Tammisaari",
    "navigate": "https://www.google.com/maps/dir/?api=1&destination=Kopparö+Tammisaari"
  },
  {
    "id": "hanko-silversand",
    "name": "Camping Silversand Hanko",
    "city": "Hanko",
    "address": "Aarne Karjalaisentie 15, 10960 Hanko",
    "description": "Ympärivuotinen neljän tähden camping-alue meren rannalla Hangossa.",
    "type": "camping",
    "url": "uusimaa-karavaanari.html#hanko",
    "map": "https://www.google.com/maps/search/?api=1&query=Camping+Silversand+Hanko",
    "navigate": "https://www.google.com/maps/dir/?api=1&destination=Aarne+Karjalaisentie+15+Hanko"
  },
  {
    "id": "nurmijarvi-saaksi",
    "name": "SFC Sääksi",
    "city": "Nurmijärvi",
    "address": "Kotorannantie 45, 05250 Nurmijärvi",
    "description": "Kaikille avoin SF-Caravan-alue Sääksjärven maisemissa.",
    "type": "camping",
    "url": "uusimaa-karavaanari.html#nurmijarvi",
    "map": "https://www.google.com/maps/search/?api=1&query=SFC+Sääksi+Nurmijärvi",
    "navigate": "https://www.google.com/maps/dir/?api=1&destination=Kotorannantie+45+Nurmijärvi"
  },
  {
    "id": "lapinjarvi-porlammi",
    "name": "Porlammin matkaparkki",
    "city": "Lapinjärvi",
    "address": "Koulupolku 8, 07820 Porlammi",
    "description": "Matkaparkki Porlammilla; saatavilla sähkö-, vesi-, WC- ja suihkupalveluja.",
    "type": "park",
    "url": "uusimaa-karavaanari.html#lapinjarvi",
    "map": "https://www.google.com/maps/search/?api=1&query=Porlammin+matkaparkki",
    "navigate": "https://www.google.com/maps/dir/?api=1&destination=Koulupolku+8+Porlammi"
  },
  {
    "id": "porvoo-byviken",
    "name": "Byviken Beach",
    "city": "Porvoo",
    "address": "Pikkuniementie 18, 06950 Porvoo",
    "description": "Rannan läheinen matkailuajoneuvoille sopiva yöpymispaikka Porvoossa.",
    "type": "park",
    "url": "porvoo-karavaanari.html",
    "map": "https://www.google.com/maps/search/?api=1&query=Byviken+Beach+Porvoo",
    "navigate": "https://www.google.com/maps/dir/?api=1&destination=Pikkuniementie+18+Porvoo"
  },
  {
    "id": "kilpisjarvi-haltinmaa",
    "name": "Haltinmaa Caravan",
    "city": "Enontekiö",
    "address": "Naalikuja 1, 99490 Kilpisjärvi",
    "description": "Ympärivuotinen caravan-alue: 14 sähköistettyä paikkaa. Hinta 25 €/vrk sisältää sähkön, veden ja WC:n.",
    "type": "camping",
    "url": "kilpisjarvi-karavaanari.html#haltinmaa",
    "map": "https://www.google.com/maps/search/?api=1&query=Haltinmaa+Caravan+Naalikuja+1+Kilpisjarvi",
    "navigate": "https://www.google.com/maps/dir/?api=1&destination=Naalikuja+1+99490+Kilpisjarvi"
  },
  {
    "id": "kilpisjarvi-tundrea",
    "name": "Tundrea Camping",
    "city": "Enontekiö",
    "address": "Kilpisjärventie 6, 99490 Kilpisjärvi",
    "description": "Ympärivuotinen camping: sähköpaikkoja matkailuautoille ja -vaunuille, huoltorakennus, sauna ja kemiallisen WC:n tyhjennys.",
    "type": "camping",
    "url": "kilpisjarvi-karavaanari.html#tundrea",
    "map": "https://www.google.com/maps/search/?api=1&query=Tundrea+Camping+Kilpisjarventie+6+Kilpisjarvi",
    "navigate": "https://www.google.com/maps/dir/?api=1&destination=Kilpisjarventie+6+99490+Kilpisjarvi"
  },
  {
    "id": "kilpisjarvi-retkeilykeskus",
    "name": "Kilpisjärven Retkeilykeskus Camping",
    "city": "Enontekiö",
    "address": "Käsivarrentie 14663, 99490 Kilpisjärvi",
    "description": "Kausittainen camping Saanan juurella matkailuautoille, vaunuille ja kesäisin teltoille. Tarkista kauden päivämäärät ennen lähtöä.",
    "type": "camping",
    "url": "kilpisjarvi-karavaanari.html#retkeilykeskus",
    "map": "https://www.google.com/maps/search/?api=1&query=Kilpisjarven+Retkeilykeskus+Käsivarrentie+14663",
    "navigate": "https://www.google.com/maps/dir/?api=1&destination=Käsivarrentie+14663+99490+Kilpisjarvi"
  },
  {
    "id": "hanko-silversand",
    "name": "Silversand Resort & Camping",
    "city": "Hanko",
    "address": "Aarne Karjalaisen tie 15, 10900 Hanko",
    "description": "Ympärivuotinen merenrantaleirintäalue ja caravan-huoltopalveluja.",
    "type": "camping",
    "url": "hanko-silversand.html",
    "map": "https://www.google.com/maps/search/?api=1&query=Silversand%20Resort%20%26%20Camping%20Hanko",
    "navigate": "https://www.google.com/maps/dir/?api=1&destination=Silversand%20Resort%20%26%20Camping%20Hanko"
  },
  {
    "id": "tammisaari-camping",
    "name": "Tammisaari Camping",
    "city": "Raasepori",
    "address": "Ormnäs, Tammisaari",
    "description": "Leirintäalue Hagenin luonnonpuiston vieressä noin 2 km keskustasta.",
    "type": "camping",
    "url": "tammisaari-camping.html",
    "map": "https://www.google.com/maps/search/?api=1&query=Tammisaari%20Camping%20Raasepori",
    "navigate": "https://www.google.com/maps/dir/?api=1&destination=Tammisaari%20Camping%20Raasepori"
  }
];