(()=>{'use strict';const places=window.caravanPlaces||[],$=id=>document.getElementById(id),requestedFilter=new URLSearchParams(window.location.search).get('type');let filter=['camping','park'].includes(requestedFilter)?requestedFilter:'all',location=null,favorites=new Set();try{const saved=JSON.parse(localStorage.getItem('ms_caravan_favorites')||'[]');if(Array.isArray(saved))favorites=new Set(saved)}catch{}
const normal=s=>s.toLocaleLowerCase('fi').normalize('NFD').replace(/[\u0300-\u036f]/g,'');
function element(tag,text,cls){const e=document.createElement(tag);if(text)e.textContent=text;if(cls)e.className=cls;return e}
function link(text,url){const a=element('a',text);a.href=url;if(url.startsWith('https://')){a.target='_blank';a.rel='noopener'}return a}
function render(){const query=normal($('search').value.trim()),city=$('city').value;const list=places.filter(p=>(!city||p.city===city)&&(!query||normal([p.name,p.city,p.address,p.description].join(' ')).includes(query))&&(filter==='all'||filter===p.type||filter==='favorites'&&favorites.has(p.id)));$('results').replaceChildren();$('count').textContent=list.length+' kohdetta';$('empty').classList.toggle('hidden',list.length>0);for(const p of list){const card=element('article',null,'place'),top=element('div',null,'placetop'),badge=element('span',(p.type==='park'?'🚐 Matkaparkki':'🏕 Leirintäalue')+' · '+p.city,'badge'),fav=element('button',favorites.has(p.id)?'♥':'♡','favorite');fav.setAttribute('aria-label',(favorites.has(p.id)?'Poista suosikeista: ':'Lisää suosikkeihin: ')+p.name);fav.setAttribute('aria-pressed',favorites.has(p.id));fav.onclick=()=>{favorites.has(p.id)?favorites.delete(p.id):favorites.add(p.id);try{localStorage.setItem('ms_caravan_favorites',JSON.stringify([...favorites]))}catch{}render()};top.append(badge,fav);card.append(top,element('h3',p.name),element('div',p.address,'address'),element('p',p.description));const buttons=element('div',null,'buttons');buttons.append(link('Kohteen tiedot →',p.url));if(p.map)buttons.append(link('Kartta ↗',p.map));if(p.navigate)buttons.append(link('Ajo-ohje ↗',p.navigate));card.append(buttons);$('results').append(card)}}
for(const city of [...new Set(places.map(p=>p.city))].sort((a,b)=>a.localeCompare(b,'fi'))){const o=element('option',city);o.value=city;$('city').append(o)}
$('search').addEventListener('input',render);$('city').addEventListener('change',()=>{render();services()});document.querySelectorAll('[data-filter]').forEach(b=>{b.setAttribute('aria-pressed',b.dataset.filter===filter);b.onclick=()=>{filter=b.dataset.filter;document.querySelectorAll('[data-filter]').forEach(x=>x.setAttribute('aria-pressed',x===b));render()}});
function mapQuery(query){const area=location?' '+location.latitude+','+location.longitude:($('city').value?' '+$('city').value:' lähellä minua');return 'https://www.google.com/maps/search/?api=1&query='+encodeURIComponent(query+area)}
function services(){document.querySelectorAll('[data-query]').forEach(a=>{a.href=mapQuery(a.dataset.query);a.target='_blank';a.rel='noopener'})}
$('near').onclick=()=>{if(!navigator.geolocation){$('locationStatus').textContent='Sijaintia ei voi käyttää tässä selaimessa. Voit valita paikkakunnan.';return}$('near').disabled=true;$('locationStatus').textContent='Haetaan sijaintia…';navigator.geolocation.getCurrentPosition(p=>{location=p.coords;$('near').disabled=false;$('locationStatus').textContent='Sijainti löytyi. Avaa karttahaku nähdäksesi lähialueen yöpymispaikat.';$('nearMap').href=mapQuery('leirintäalue matkaparkki');$('nearMap').classList.remove('hidden');services()},()=>{$('near').disabled=false;$('locationStatus').textContent='Sijaintia ei saatu. Valitse paikkakunta tai hae nimellä.'},{enableHighAccuracy:false,timeout:10000,maximumAge:300000})};services();render();})();
