window.caravanPlaces=[
  {"id":"asikkala-kanavaanari","name":"Kanavaanari – Vääksyn matkaparkki","city":"Asikkala","address":"Melakuja 4, 17200 Vääksy","description":"Matkaparkki Vääksyn kanavan ja Päijännetalon lähellä.","type":"park","url":"asikkala-kanavaanari.html","map":"","navigate":""},
  {"id":"camping-tallukka","name":"Tallukan matkaparkki","city":"Asikkala","address":"Tallukantie 1, 17200 Vääksy","description":"Matkaparkki Hotelli Tallukan yhteydessä.","type":"park","url":"camping-tallukka.html","map":"https://www.google.com/maps/search/?api=1&query=Tallukan+matkaparkki+Tallukantie+1%2C+17200+V%C3%A4%C3%A4ksy","navigate":"https://www.google.com/maps/dir/?api=1&destination=Tallukantie+1%2C+17200+V%C3%A4%C3%A4ksy"},
  {"id":"camping-koskenniemi","name":"Camping Koskenniemi","city":"Hartola","address":"Koskenniementie 66, 19600 Hartola","description":"Leirintäalue ja majoituspalveluja Hartolassa.","type":"camping","url":"camping-koskenniemi.html","map":"https://www.google.com/maps/search/?api=1&query=Camping+Koskenniemi+Koskenniementie+66%2C+19600+Hartola","navigate":"https://www.google.com/maps/dir/?api=1&destination=Koskenniementie+66%2C+19600+Hartola"},
  {"id":"heinola-heinasaari","name":"Camping Heinolan Heinäsaari","city":"Heinola","address":"Heinäsaarentie 101, 18100 Heinola","description":"Leirintäalue, caravan-paikat, mökit, saunat ja ravintolapalveluja vesistömaisemissa.","type":"camping","url":"heinola-heinasaari.html","map":"https://www.google.com/maps/search/?api=1&query=Camping+Heinolan+Hein%C3%A4saari+Hein%C3%A4saarentie+101%2C+18100+Heinola","navigate":"https://www.google.com/maps/dir/?api=1&destination=Hein%C3%A4saarentie+101%2C+18100+Heinola"},
  {"id":"camping-vidnas","name":"Camping Vidnäs","city":"Heinola","address":"Viikinäistentie 203 A, 19210 Lusi","description":"Pieni leirintäalue maaseudun rauhassa järven rannalla; myös telttapaikkoja.","type":"camping","url":"camping-vidnas.html","map":"https://www.google.com/maps/search/?api=1&query=Camping+Vidn%C3%A4s+Viikin%C3%A4istentie+203+A%2C+19210+Lusi","navigate":"https://www.google.com/maps/dir/?api=1&destination=Viikin%C3%A4istentie+203+A%2C+19210+Lusi"},
  {"id":"hollola-messila","name":"Camping Messilä","city":"Hollola","address":"Rantatie 5, 15980 Messilä","description":"Camping-alue Vesijärven rannalla matkailuautoille, vaunuille ja telttailuun.","type":"camping","url":"hollola-messila.html","map":"https://www.google.com/maps/search/?api=1&query=Camping+Messil%C3%A4+Rantatie+5%2C+15980+Messil%C3%A4","navigate":"https://www.google.com/maps/dir/?api=1&destination=Rantatie+5%2C+15980+Messil%C3%A4"},
  {"id":"camping-leininranta","name":"SFC Leininranta","city":"Iitti","address":"Siestantie 85, 47400 Kausala","description":"SF-Caravan-alue Iitissä. Tarkista vierailuehdot ja aukiolo ennen saapumista.","type":"camping","url":"camping-leininranta.html","map":"https://www.google.com/maps/search/?api=1&query=SFC+Leininranta+Siestantie+85%2C+47400+Kausala","navigate":"https://www.google.com/maps/dir/?api=1&destination=Siestantie+85%2C+47400+Kausala"},
  {"id":"camping-kangaslampi","name":"SFC Kangaslampi","city":"Lahti","address":"Alhaistentie 77, 15560 Nastola","description":"Caravan- ja leirintäalue Lahden Nastolassa. Tarkista vierailuehdot ennen saapumista.","type":"camping","url":"camping-kangaslampi.html","map":"https://www.google.com/maps/search/?api=1&query=SFC+Kangaslampi+Alhaistentie+77%2C+15560+Nastola","navigate":"https://www.google.com/maps/dir/?api=1&destination=Alhaistentie+77%2C+15560+Nastola"},
  {"id":"camping-hennala","name":"Hennalan matkaparkki","city":"Lahti","address":"Pataljoonankatu 3, 15700 Lahti","description":"Kaupunkimatkaparkki Hennalan alueella.","type":"park","url":"camping-hennala.html","map":"https://www.google.com/maps/search/?api=1&query=Hennalan+matkaparkki+Pataljoonankatu+3%2C+15700+Lahti","navigate":"https://www.google.com/maps/dir/?api=1&destination=Pataljoonankatu+3%2C+15700+Lahti"},
  {"id":"camping-herrasmanni","name":"Herrasmannin leirintäalue","city":"Lahti","address":"Herrasmanninkatu 20, 15210 Lahti","description":"Leirintä- ja caravan-alue Alasenjärven rannalla.","type":"camping","url":"camping-herrasmanni.html","map":"https://www.google.com/maps/search/?api=1&query=Herrasmannin+leirint%C3%A4alue+Herrasmanninkatu+20%2C+15210+Lahti","navigate":"https://www.google.com/maps/dir/?api=1&destination=Herrasmanninkatu+20%2C+15210+Lahti"},
  {"id":"camping-lokki","name":"Ravintola Lokin matkaparkki","city":"Lahti","address":"Jalkarannantie 19, 15900 Lahti","description":"Matkaparkki Vesijärven ja sataman läheisyydessä.","type":"park","url":"camping-lokki.html","map":"https://www.google.com/maps/search/?api=1&query=Ravintola+Lokin+matkaparkki+Jalkarannantie+19%2C+15900+Lahti","navigate":"https://www.google.com/maps/dir/?api=1&destination=Jalkarannantie+19%2C+15900+Lahti"},
  {"id":"camping-telaranta","name":"Lomakeskus Telaranta Camping","city":"Padasjoki","address":"Porasantie 176, 17500 Padasjoki","description":"Camping- ja lomakeskus Padasjoen luonnon keskellä.","type":"camping","url":"camping-telaranta.html","map":"https://www.google.com/maps/search/?api=1&query=Lomakeskus+Telaranta+Camping+Porasantie+176%2C+17500+Padasjoki","navigate":"https://www.google.com/maps/dir/?api=1&destination=Porasantie+176%2C+17500+Padasjoki"},
  {"id":"camping-mainiemi","name":"Mainiemi Caravan","city":"Padasjoki","address":"Pykäläniementie 10, 17500 Padasjoki","description":"Caravan-alue Padasjoella. Tarkista vierailuehdot ja aukiolo ennen saapumista.","type":"camping","url":"camping-mainiemi.html","map":"https://www.google.com/maps/search/?api=1&query=Mainiemi+Caravan+Pyk%C3%A4l%C3%A4niementie+10%2C+17500+Padasjoki","navigate":"https://www.google.com/maps/dir/?api=1&destination=Pyk%C3%A4l%C3%A4niementie+10%2C+17500+Padasjoki"},
  {"id":"camping-mylly-makela","name":"SFC Mylly-Mäkelä","city":"Padasjoki","address":"Mylly-Mäkeläntie 14, 17530 Arrakoski","description":"Ympärivuotinen caravan- ja leirintäalue järven ja kosken äärellä.","type":"camping","url":"camping-mylly-makela.html","map":"https://www.google.com/maps/search/?api=1&query=SFC+Mylly-M%C3%A4kel%C3%A4+Mylly-M%C3%A4kel%C3%A4ntie+14%2C+17530+Arrakoski","navigate":"https://www.google.com/maps/dir/?api=1&destination=Mylly-M%C3%A4kel%C3%A4ntie+14%2C+17530+Arrakoski"},
  {"id":"camping-vuorenmaki","name":"SFC Vuorenmäki","city":"Orimattila","address":"Salmelantie 178, 16200 Artjärvi","description":"Ympärivuotinen caravanalue Villikkalanjärven läheisyydessä Artjärvellä.","type":"camping","url":"camping-vuorenmaki.html","map":"https://www.google.com/maps/search/?api=1&query=SFC+Vuorenm%C3%A4ki+Salmelantie+178%2C+16200+Artj%C3%A4rvi","navigate":"https://www.google.com/maps/dir/?api=1&destination=Salmelantie+178%2C+16200+Artj%C3%A4rvi"},
  {"id":"camping-sysma","name":"Camping Sysmä","city":"Sysmä","address":"Huitilantie 3, 19700 Sysmä","description":"Leirintäalue Päijänteen rannalla matkailuautoille, vaunuille, teltoille ja mökkimajoitukseen.","type":"camping","url":"camping-sysma.html","map":"https://www.google.com/maps/search/?api=1&query=Camping+Sysm%C3%A4+Huitilantie+3%2C+19700+Sysm%C3%A4","navigate":"https://www.google.com/maps/dir/?api=1&destination=Huitilantie+3%2C+19700+Sysm%C3%A4"}
];
