const MAAKUNNAT = {
  "paijat-hame": {
    nimi: "Päijät-Häme",
    vaakuna: "vaakuna-paijat-hame.svg",
    kunnat: ["asikkala","hartola","heinola","hollola","iitti","karkola","lahti","orimattila","padasjoki","sysma"],
    kuvaus: "Järviä, harjuja, kanavia, kaupunkikulttuuria ja retkikohteita Suomen sydämessä."
  }
};

const KUNNAT = {
  asikkala: { nimi:"Asikkala", maakunta:"Päijät-Häme", tyyppi:\"Kunta\", asukkaita:\"n. 7 900\", vaakuna:"vaakuna-asikkala.svg", sivu:"asikkala.html", tunnus:"Vääksyn kanava, Pulkkilanharju ja Päijänteen maisemat", palvelut:['Matkaparkit', 'Luonto ja retkeily', 'Kahvilat ja ravintolat', 'Kaupat ja palvelut', 'Autoilijan palvelut'] },
  hartola: { nimi:"Hartola", maakunta:"Päijät-Häme", tyyppi:\"Kunta\", asukkaita:\"n. 2 500\", vaakuna:"vaakuna-hartola.svg", sivu:"hartola.html", tunnus:"Kuninkaanpitäjä, Itä-Hämeen museo ja järvimaisemat", palvelut:['Nähtävyydet', 'Luonto ja retkeily', 'Kahvilat ja ravintolat', 'Palvelut', 'Tarina'] },
  heinola: { nimi:"Heinola", maakunta:"Päijät-Häme", tyyppi:\"Kaupunki\", asukkaita:\"n. 17 700\", vaakuna:"vaakuna-heinola.svg", sivu:"heinola.html", tunnus:"Jyrängönvirta, Harjupaviljonki, lintutarha ja satama", palvelut:['Nähtävyydet', 'Karavaanarille', 'Luonto ja retkeily', 'Kahvilat ja ravintolat', 'Tarina'] },
  hollola: { nimi:"Hollola", maakunta:"Päijät-Häme", tyyppi:\"Kunta\", asukkaita:\"n. 22 800\", vaakuna:"vaakuna-hollola.svg", sivu:"hollola.html", tunnus:"Keskiaikainen kirkko, Messilä, Tiirismaa ja Salpausselkä", palvelut:['Nähtävyydet', 'Luonto ja retkeily', 'Karavaanarille ja majoitus', 'Kahvilat ja ravintolat', 'Tarina'] },
  iitti: { nimi:"Iitti", maakunta:"Päijät-Häme", tyyppi:\"Kunta\", asukkaita:\"n. 6 500\", vaakuna:"vaakuna-iitti.svg", sivu:"iitti.html", tunnus:"Hiidenvuori, Kymijoki, Vuolenkoski ja Kimolan kanava", palvelut:['Luonto ja retkeily', 'Nähtävyydet', 'Kahvilat ja ravintolat', 'Karavaanarille ja majoitus', 'Tarina'] },
  karkola: { nimi:"Kärkölä", maakunta:"Päijät-Häme", tyyppi:\"Kunta\", asukkaita:\"n. 4 100\", vaakuna:"vaakuna-karkola.svg", sivu:"karkola.html", tunnus:"Huovilan puisto, Järvelä ja rauhalliset kylämaisemat", palvelut:['Nähtävyydet', 'Luonto ja retkeily', 'Kahvilat ja ravintolat', 'Palvelut', 'Tarina'] },
  lahti: { nimi:"Lahti", maakunta:"Päijät-Häme", tyyppi:\"Kaupunki\", asukkaita:\"n. 121 000\", vaakuna:"vaakuna-lahti.svg", sivu:"lahti.html", tunnus:"Vesijärven satama, Salpausselkä, kulttuuri ja kaupunkipalvelut", palvelut:['Nähtävyydet', 'Luonto ja retkeily', 'Kahvilat ja ravintolat', 'Palvelut', 'Tarina'] },
  orimattila: { nimi:"Orimattila", maakunta:"Päijät-Häme", tyyppi:\"Kaupunki\", asukkaita:\"n. 15 600\", vaakuna:"vaakuna-orimattila.svg", sivu:"orimattila.html", tunnus:"Taidemuseo, Kehräämö, kylät ja maaseutureitit", palvelut:['Nähtävyydet', 'Luonto ja retkeily', 'Kahvilat ja ravintolat', 'Palvelut', 'Tarina'] },
  padasjoki: { nimi:"Padasjoki", maakunta:"Päijät-Häme", tyyppi:\"Kunta\", asukkaita:\"n. 2 800\", vaakuna:"vaakuna-padasjoki.svg", sivu:"padasjoki.html", tunnus:"Päijänteen kansallispuisto, Kelvenne, satama ja järvimaisemat", palvelut:['Nähtävyydet', 'Luonto ja retkeily', 'Karavaanarille ja majoitus', 'Kahvilat ja ravintolat', 'Tarina'] },
  sysma: { nimi:"Sysmä", maakunta:"Päijät-Häme", tyyppi:\"Kunta\", asukkaita:\"n. 3 500\", vaakuna:"vaakuna-sysma.svg", sivu:"sysma.html", tunnus:"Kammiovuori, Päijätsalo, Suopelto ja Tainionvirta", palvelut:['Luonto ja retkeily', 'Nähtävyydet', 'Kahvilat ja ravintolat', 'Karavaanarille ja majoitus', 'Tarina'] }
};

const HAKU = [
  ...Object.values(KUNNAT).map(k => ({nimi:k.nimi, url:k.sivu, tyyppi:'Kunta'})),
  {nimi:'Päijät-Häme', url:'paijat-hame.html', tyyppi:'Maakunta'},
  {nimi:'Vääksyn kanava ja Vanha Vääksy', url:'asikkala.html', tyyppi:'Kohde'},
  {nimi:'Pulkkilanharju', url:'asikkala.html', tyyppi:'Kohde'},
  {nimi:'Päijännetalo', url:'asikkala.html', tyyppi:'Kohde'},
  {nimi:'Aurinkovuori', url:'asikkala.html', tyyppi:'Kohde'},
  {nimi:'Urajärven kartanomuseo', url:'asikkala.html', tyyppi:'Kohde'},
  {nimi:'Vesijärven satama', url:'lahti.html', tyyppi:'Kohde'},
  {nimi:'Sibeliustalo', url:'lahti.html', tyyppi:'Kohde'},
  {nimi:'Malva', url:'lahti.html', tyyppi:'Kohde'},
  {nimi:'Lahden urheilukeskus ja hyppyrimäet', url:'lahti.html', tyyppi:'Kohde'},
  {nimi:'Salpausselän ulkoilumaastot', url:'lahti.html', tyyppi:'Kohde'},
  {nimi:'Harjupaviljonki', url:'heinola.html', tyyppi:'Kohde'},
  {nimi:'Heinolan lintuhoitola', url:'heinola.html', tyyppi:'Kohde'},
  {nimi:'Heinolan satama', url:'heinola.html', tyyppi:'Kohde'},
  {nimi:'Heinolan kansallinen kaupunkipuisto', url:'heinola.html', tyyppi:'Kohde'},
  {nimi:'Vierumäki', url:'heinola.html', tyyppi:'Kohde'},
  {nimi:'Hollolan keskiaikainen kivikirkko', url:'hollola.html', tyyppi:'Kohde'},
  {nimi:'Tiirismaa', url:'hollola.html', tyyppi:'Kohde'},
  {nimi:'Kapatuosian linnavuori', url:'hollola.html', tyyppi:'Kohde'},
  {nimi:'Messilä', url:'hollola.html', tyyppi:'Kohde'},
  {nimi:'Kiikunlähde', url:'hollola.html', tyyppi:'Kohde'},
  {nimi:'Päijänteen kansallispuisto', url:'padasjoki.html', tyyppi:'Kohde'},
  {nimi:'Kelvenne', url:'padasjoki.html', tyyppi:'Kohde'},
  {nimi:'Padasjoen satama', url:'padasjoki.html', tyyppi:'Kohde'},
  {nimi:'Melonta ja vesiretket', url:'padasjoki.html', tyyppi:'Kohde'},
  {nimi:'Vesijako ja kylämaisemat', url:'padasjoki.html', tyyppi:'Kohde'},
  {nimi:'Kammiovuori', url:'sysma.html', tyyppi:'Kohde'},
  {nimi:'Päijätsalo', url:'sysma.html', tyyppi:'Kohde'},
  {nimi:'Suopelto', url:'sysma.html', tyyppi:'Kohde'},
  {nimi:'Sysmän kirkko', url:'sysma.html', tyyppi:'Kohde'},
  {nimi:'Tainionvirta', url:'sysma.html', tyyppi:'Kohde'},
  {nimi:'Itä-Hämeen museo', url:'hartola.html', tyyppi:'Kohde'},
  {nimi:'Koskipään kartano', url:'hartola.html', tyyppi:'Kohde'},
  {nimi:'Kuninkaanpitäjä', url:'hartola.html', tyyppi:'Kohde'},
  {nimi:'Järvimaisemat', url:'hartola.html', tyyppi:'Kohde'},
  {nimi:'Hartolan golf- ja vapaa-ajan palvelut', url:'hartola.html', tyyppi:'Kohde'},
  {nimi:'Hiidenvuori', url:'iitti.html', tyyppi:'Kohde'},
  {nimi:'Kimolan kanava', url:'iitti.html', tyyppi:'Kohde'},
  {nimi:'Radansuun luontopolku', url:'iitti.html', tyyppi:'Kohde'},
  {nimi:'Vuolenkoski', url:'iitti.html', tyyppi:'Kohde'},
  {nimi:'Kausala', url:'iitti.html', tyyppi:'Kohde'},
  {nimi:'Huovilan puisto', url:'karkola.html', tyyppi:'Kohde'},
  {nimi:'Järvelä', url:'karkola.html', tyyppi:'Kohde'},
  {nimi:'Kärkölän kirkko', url:'karkola.html', tyyppi:'Kohde'},
  {nimi:'Kylä- ja maalaismaisemat', url:'karkola.html', tyyppi:'Kohde'},
  {nimi:'Järvelän asemanseutu', url:'karkola.html', tyyppi:'Kohde'},
  {nimi:'Orimattilan taidemuseo', url:'orimattila.html', tyyppi:'Kohde'},
  {nimi:'Kehräämö', url:'orimattila.html', tyyppi:'Kohde'},
  {nimi:'Orimattilan kirkko', url:'orimattila.html', tyyppi:'Kohde'},
  {nimi:'Kylä- ja maaseutumaisemat', url:'orimattila.html', tyyppi:'Kohde'},
  {nimi:'Keskustan palvelut', url:'orimattila.html', tyyppi:'Kohde'}
];
