(()=>{'use strict';
const extra={name:'Pyynikin munkkikahvila ja näkötorni',city:'Tampere',address:'Näkötornintie 20, Tampere',description:'Munkki- ja kahvitauko Pyynikin näkötornin juurella sekä järvimaisemia tornista.',type:'stop',url:'tampere-pyynikin-munkkikahvila.html'};
const seen=new Set(), places=[...(window.nearbyData||[]),...(window.visitHighlights||[]),extra].filter(p=>{if(!['sight','stop'].includes(p.type)||!p.url)return false;const key=p.city+'|'+p.url;if(seen.has(key))return false;seen.add(key);return true;});
const city=document.getElementById('city'),query=document.getElementById('query'),results=document.getElementById('results'),count=document.getElementById('count');
const norm=s=>String(s||'').toLocaleLowerCase('fi').normalize('NFD').replace(/[\u0300-\u036f]/g,'');
const cities=[...new Set(places.map(p=>p.city))].sort((a,b)=>a.localeCompare(b,'fi'));
for(const c of cities){const o=document.createElement('option');o.value=c;o.textContent=c;city.append(o);}
const wanted=new URLSearchParams(location.search).get('kunta');if(cities.includes(wanted))city.value=wanted;
function render(){const q=norm(query.value.trim());const matches=places.filter(p=>(!city.value||city.value===p.city)&&norm([p.name,p.city,p.address,p.description].join(' ')).includes(q)).sort((a,b)=>a.city.localeCompare(b.city,'fi')||a.name.localeCompare(b.name,'fi'));results.replaceChildren();count.textContent=(city.value||'Koko Suomi')+' · '+matches.length+' käyntikohdetta';for(const p of matches){const a=document.createElement('a');a.className='place';a.href=p.url;const name=document.createElement('strong');name.textContent=p.name;const meta=document.createElement('small');meta.textContent=p.city+' · '+(p.type==='stop'?'Pysähdy matkalla':'Nähtävyys tai retkikohde');const desc=document.createElement('p');desc.textContent=p.description;const more=document.createElement('span');more.textContent='Tutustu →';a.append(name,meta,desc,more);results.append(a);}if(!matches.length){const p=document.createElement('p');p.textContent='Kohteita ei löytynyt. Kokeile toista nimeä tai valitse kaikki paikkakunnat.';results.append(p);}}
city.addEventListener('change',()=>{const u=new URL(location.href);if(city.value)u.searchParams.set('kunta',city.value);else u.searchParams.delete('kunta');history.replaceState(null,'',u);render();});query.addEventListener('input',render);render();
})();
